name: Sanity check
run-name: Sanity check
on:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: chrisdsa/rust:1.68-0.1.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    container:
      image: chrisdsa/rust:1.68-0.1.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    container:
      image: chrisdsa/rust:1.68-0.1.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --all

  version:
    runs-on: ubuntu-latest
    container:
      image: chrisdsa/rust:1.68-0.1.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - run: ./script/assert_version
